<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="RAKESH-ACER" failures="0" tests="4" name="User TestCases" time="2.758" errors="0" timestamp="2023-12-14T13:50:03 IST">
  <testcase classname="core.BaseTest" name="@AfterMethod getResult" time="0.002">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at core.BaseTest.getResult(BaseTest.java:27)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod getResult -->
  <testcase classname="userManagement.GetPost" name="basicauth" time="2.722"/>
  <testcase classname="userManagement.GetPost" name="getdatafromjson" time="0.0">
    <skipped/>
  </testcase> <!-- getdatafromjson -->
  <testcase classname="userManagement.GetPost" name="postdatarestassured" time="0.0">
    <skipped/>
  </testcase> <!-- postdatarestassured -->
  <testcase classname="userManagement.GetPost" name="postwithpojo" time="0.0">
    <skipped/>
  </testcase> <!-- postwithpojo -->
</testsuite> <!-- User TestCases -->
